[mgr]
append_keymap = [
    { on = "T", run = 'shell --orphan --confirm alacritty', desc = "Open terminal at current dir" },
    { on = "<Tab>", run = "tab_switch 1 --relative", desc = "Switch to next tab" },
    { on = "<BackTab>", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
    { on = "<C-w>", run = "close", desc = "close tab" },
]
