# Based on https://github.com/sxyazi/yazi/blob/main/config/preset/yazi.toml
# Docs: https://yazi-rs.github.io/docs/usage/configuration/yazi

[manager]
layout         = [ 1, 4, 3 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
sort_translit  = true
show_hidden    = false
show_symlink   = true

[opener]
folder = [
	{ exec = 'alacritty -e yazi "$@"', block = false, orphan = true },
]
video = [
	{ exec = 'vlc "$@"', block = false, orphan = true },
]
audio = [
	{ exec = 'vlc "$@"', block = false, orphan = true },
]
pdf = [
	{ exec = 'firefox -P PdfViewer "$@"', block = false, orphan = true },
]
image = [
	{ exec = 'feh "$@"', block = false, orphan = true },
]
text = [
	{ exec = 'nvim "$@"', block = true },
]
sheet = [
    { exec = 'libreoffice --calc "$@"', block = false, orphan = true },
]
word = [
    { exec = 'libreoffice --writer "$@"', block = false, orphan = true },
]
slide = [
    { exec = 'libreoffice --impress "$@"', block = false, orphan = true },
]
fallback = [
	{ exec = ':' }
]

[open]
rules = [
	{ name = "*/", use = "folder" },
    { name = "*.ods", use = "sheet" },
    { name = "*.odt", use = "sheet" },
    { name = "*.xlsx", use = "sheet" },
    { name = "*.xls", use = "sheet" },
    { name = "*.csv", use = "sheet" },

    { name = "*.docx", use = "word" },
    { name = "*.doc", use = "word" },
    { name = "*.rtf", use = "word" },
    { name = "*.wpd", use = "word" },

    { name = "*.pptx", use = "slide" },
    { name = "*.ppt", use = "slide" },
    { name = "*.ppmx", use = "slide" },
    { name = "*.ppm", use = "slide" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },
	{ mime = "application/pdf", use = "pdf" },

	{ mime = "*", use = "fallback" },
]
