import = ["/home/amurphy/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5
